#!/bin/bash

git fetch
remoteBranch=$(git symbolic-ref --short -q HEAD)

if [ ! -z "$1" ]
then
    remoteBranch=$1
fi
echo "Showing logs between $remoteBranch and origin/$remoteBranch"
git log $remoteBranch..origin/$remoteBranch --oneline