#!/bin/bash

git fetch
remoteBranch=$(git symbolic-ref --short -q HEAD)

if [ -n "$1" ]
then
    remoteBranch=$1
fi
echo "Showing diff between ${remoteBranch} and origin/${remoteBranch}"
git diff "${remoteBranch}"..origin/"${remoteBranch}"