name: Main workflow

on:
  pull_request:
    paths:
      - 'Makefile'
      - '**.sh'
      - '**.bash'
      - 'git/cmd/*'
  push:
    branches:
      - 'master'
    paths:
      - 'Makefile'
      - '**.sh'
      - '**.bash'
      - 'git/cmd/*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install shellcheck
        run: brew install shellcheck

      - name: Run Test
        run: ./test.sh
